name: Deploy Docs Test

on:
  workflow_dispatch:

jobs:
  context:
    runs-on: ubuntu-latest
    steps:
       - name: Dump github context
         run:   echo "$GITHUB_CONTEXT"
         shell: bash
         env:
           GITHUB_CONTEXT: ${{ toJson(github) }}
  deploy-doocs:
    uses: spring-cloud/spring-cloud-build/.github/workflows/spring-cloud-deploy-docs.yml@v1
