name: Spring Cloud Deploy Docs

on:
  workflow_call:

permissions:
  actions: write
jobs:
  build:
    runs-on: ubuntu-latest
    # FIXME: enable when pushed to spring-projects
    # if: github.repository_owner == 'spring-projects'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: docs-build
          fetch-depth: 1
      # TODO: Do we need these two below jobs?  They don't appear to do much when they run
      - name: Dispatch (partial build)
        if: github.ref_type == 'branch'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh workflow run deploy-docs.yml -r $(git rev-parse --abbrev-ref HEAD) -f build-refname=${{ github.ref_name }}
      - name: Dispatch (full build)
        if: github.ref_type == 'tag'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh workflow run deploy-docs.yml -r $(git rev-parse --abbrev-ref HEAD)
